// User Register
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

// User Login
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// Open Bank Account
export const OPEN_ACCOUNT_START = 'OPEN_ACCOUNT_START';
export const OPEN_ACCOUNT_SUCCESS = 'OPEN_ACCOUNT_SUCCESS';
export const OPEN_ACCOUNT_FAILURE = 'OPEN_ACCOUNT_FAILURE';

